config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :api do
    namespace :v1 do
      resource :token, only: :create
      resources :stories, only: [:create, :index]
    end
  end

  resources :profiles, only: :show do
    get "/favorites", action: :favorites, as: :favorites
    get "/negatives", action: :negatives, as: :negatives
    get "/commented", action: :commented, as: :commented
  end

  resource :notification_setting, only: :update

  resources :stories do
    put :positive
    put :negative
  end

  resources :comments

  get "/feed" => "home#feed", :as => "feed"

  root "home#index"
end

app/views/shared/_error_messages.html.erb
<% if record.errors.any? %>
  <div class="alert alert-error alert-danger">
    <a class="close" data-dismiss="alert">×</a>
    <ul>
      <% record.errors.full_messages.each do |message| %>
        <li>
          <%= raw message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_facebook_api.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&appId=<%= ENV['FACEBOOK_APP_ID'] %>&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/shared/_flash_messages.html.erb
<% if notice   %>
  <p class="notice alert alert-success message">
    <a class="close" data-dismiss="alert">×</a>
    <%= notice %>
  </p>
<% end %>

<% if alert %>
  <p class="notice alert alert-danger message">
    <a class="close" data-dismiss="alert">×</a>
    <b>ATENÇÃO:</b> <%= alert %>
  </p>
<% end %>

app/views/shared/_google_analytics.html.erb
<% if ENV['GOOGLE_ANALYTICS_ID'] %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '<%= ENV['GOOGLE_ANALYTICS_ID'] %>', 'auto');
    ga('send', 'pageview');

  </script>
<% end %>

app/views/shared/_header.html.erb
<div id="header" class="link_title">
  <div class="row">
    <div class="col-md-6">
      <h1>
        <%= link_to "https://tasafo.org" do %>
          <%= image_tag "logo-maozinha-tasafo.png", height: 65 %>
        <% end %>
        <%= link_to "BizuSafo", root_path %>
      </h1>
    </div>
    <div class="col-md-4 main-menu-buttom">
      <% unless user_signed_in? %>
        <%= link_to "Entrar", new_user_session_path, class: "btn btn-lg btn-info" %>
        <%= link_to "Cadastre-se", new_user_registration_path, class: "btn btn-lg btn-success" %>
      <% end %>
    </div>
    <div class="col-md-2 hidden-sm hidden-xs" id="extension">
      <%= link_to t(:download_extension), "https://chrome.google.com/webstore/detail/bizusafo/egcodpfgnhacifeonmhfpgnbddalnlck", target: "_blank" %>
      <%= image_tag "chrome_icon.png" %>
    </div>
  </div>
</div>

app/views/shared/_main_menu.html.erb
<%= link_to root_path, class: "btn btn-lg btn-default", title: "Bizuuus" do %>
  <span class="glyphicon glyphicon-th-list"></span>
  <p class="label-menu">Bizus</p>
<% end %>

<% if user_signed_in? %>
  <%= link_to new_story_path, class: "btn btn-lg btn-default", title: "Novo Bizuuu!!!" do %>
    <span class="glyphicon glyphicon-bullhorn"></span>
    <p class="label-menu">Novo</p>
  <% end %>
  <%= link_to profile_path(current_user), class: "btn btn-lg btn-default", title: "Perfil" do %>
    <span class="glyphicon glyphicon-user"></span>
    <p class="label-menu">Perfil</p>
  <% end %>
  <%= link_to destroy_user_session_path, class: "btn btn-lg btn-default", title: "Sair", :method => :delete do %>
    <span class="glyphicon glyphicon-off"></span>
    <p class="label-menu">Sair</p>
  <% end %>
<% else %>
  <%= link_to new_user_session_path, class: "btn btn-lg btn-default", title: "Entrar" do %>
    <span class="glyphicon glyphicon-user"></span>
    <p class="label-menu">Entrar</p>
  <% end %>
<% end %>

app/views/shared/_profile.html.erb
<section id="profile-info">
  <div class="row">
    <div class="col-md-12">
      <article>
        <%= image_tag avatar_url(@user), class: "user-photo" %>
      </article>

      <article>
        <p>
          <strong><%= t("activerecord.attributes.user.username") %>:</strong>
          <span><%= @user.username %></span>
        </p>
        <p>
          <strong>E-mail:</strong>
          <span><%= @user.email %></span>
        </p>
        <p>
          <strong><%= @user.stories.count %> bizuuus!</strong>
        </p>
      </article>

      <% if current_user == @user %>
        <aside>
          <%= link_to t("profile.edit"), edit_user_registration_path %>
        </aside>
      <% end %>
    </div>
  </div>
</section>

app/views/shared/_profile_menu.html.erb
<div id="profile-menu">
  <ul class="nav nav-tabs" role="tablist">
    <li class="<%= profile_show_tab_class %>"><%= link_to "Bizus", profile_path(@user) %></li>
    <li class="<%= profile_favorite_tab_class %>"><%= link_to "Favoritos", profile_favorites_path(@user) %></li>
    <li class="<%= profile_negative_tab_class %>"><%= link_to "Rebaixados", profile_negatives_path(@user) %></li>
    <li class="<%= profile_comment_tab_class %>"><%= link_to "Comentados", profile_commented_path(@user) %></li>
  </ul>
</div>

app/views/shared/_story_filters.html.erb
<nav id="story_filters" class="row">
  <div class="col-lg-12">
    <div class="filters form-inline">
        <div class="form-group">
          <span>Ordenar por:</span>
          <%= select_tag :order, options_for_select([["novos", :by_date], ["votos", :by_rating]], selected_filter("order")), class: "form-control" %>
        </div>
        <div class="form-group">
          <span>Filtrar por:</span>
          <%= select_tag :filter, options_for_select([["todos", :timeline], ["este mês", :by_current_month], ["esta semana", :by_current_week]], selected_filter("filter")), class: "form-control" %>
        </div>
    </div>

    <div class="filters">
      <span>Tags:</span>
      <ul>
        <% if params[:tags].present? %>
          <li>
            <% params[:tags].split(",").map(&:strip).each do |tag| %>
              <span class="label label-primary"><%= tag %></span>
            <% end %>
            <%= link_to "remover tags", current_filtered_url(order: params[:order], filter: params[:filter]) %>
          </li>
        <% else %>
          <li>
            <%= form_for :search, method: :get, html: { class: "form-inline" } do |f| %>
              <%= text_field_tag :tags, nil, class: "form-control input-sm" %>
              <%= f.button "Ok", class: "btn btn-default btn-sm" %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>