config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :api do
    namespace :v1 do
      resource :token, only: :create
      resources :stories, only: [:create, :index]
    end
  end

  resources :profiles, only: :show do
    get "/favorites", action: :favorites, as: :favorites
    get "/negatives", action: :negatives, as: :negatives
    get "/commented", action: :commented, as: :commented
  end

  resource :notification_setting, only: :update

  resources :stories do
    put :positive
    put :negative
  end

  resources :comments

  get "/feed" => "home#feed", :as => "feed"

  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @stories = Story::Filter.new.filter(params)
  end

  def feed
    @stories = Story.all
    respond_to do |format|
      format.rss { render layout: false }
      format.atom { render 'feed.rss', layout: false }
      format.html { render 'feed.rss', layout: false }
    end
  end
end

app/views/home/_story.html.erb
<div class="story-container">
  <div class="row">
    <div class="col-md-9 story-description">
      <div class="lead">
        <%= link_to story.description, story.url, target: "_blank" %>
      </div>
    </div>
    <div class="col-md-3">
      <div id="story-votes-<%=story.id%>" class="story-ratings">
        <%= render partial: "ratings", locals: {story: story} %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 comments-status">
      <%= link_to "#{story.comments.count} Comentários", story %>
    </div>

    <div class="col-md-6 time-container">
      <%= image_tag avatar_url(story.user), class: "user-photo" %>
      <span>
        <%= story.user.username %> <strong>em</strong> <%= l story.created_at %>
        <% if story.user == current_user %>
          |
          <%= link_to "editar", edit_story_path(story) %>
        <% end %>
      </span>
    </div>
  </div>
</div>

app/views/home/_story_filters.html.erb
<nav id="story_filters" class="row">
  <div class="col-lg-12">
    <div class="filters">
      <span>Ordenar por:</span>
      <ul>
        <li><%= story_filter_handler "novos", :order, :by_date %></li>
        <li><%= story_filter_handler "votos", :order, :by_rating %></li>
        <li>|</li>
        <li><%= story_filter_handler "todos",       :filter, :timeline %></li>
        <li><%= story_filter_handler "este mês",    :filter, :by_current_month %></li>
        <li><%= story_filter_handler "esta semana", :filter, :by_current_week %></li>
      </ul>
    </div>

    <div class="filters">
      <span>Tags:</span>
      <ul>
        <% if params[:tags].present? %>
          <li>
            <% params[:tags].split(",").map(&:strip).each do |tag| %>
              <span class="label label-primary"><%= tag %></span>
            <% end %>
            <%= link_to "remover tags", root_path(order: params[:order], filter: params[:filter]) %>
          </li>
        <% else %>
          <li>
            <%= form_for :search, method: :get, html: { class: "form-inline" } do |f| %>
              <%= text_field_tag :tags, nil, class: "form-control input-sm" %>
              <%= f.button "Ok", class: "btn btn-default btn-sm" %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<%= render "shared/story_filters" %>

<% if @stories.any? %>
  <div id="stories-container">
    <%= render partial: "stories/story", collection: @stories, locals: { show_comments: false, full_description: false } %>
  </div>
<% else %>
  <div class="well">
    <%= t("story.no_story") %>
  </div>
<% end %>

<div class="center-block pagintation-center">
  <%= paginate @stories %>
</div>