config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :api do
    namespace :v1 do
      resource :token, only: :create
      resources :stories, only: [:create, :index]
    end
  end

  resources :profiles, only: :show do
    get "/favorites", action: :favorites, as: :favorites
    get "/negatives", action: :negatives, as: :negatives
    get "/commented", action: :commented, as: :commented
  end

  resource :notification_setting, only: :update

  resources :stories do
    put :positive
    put :negative
  end

  resources :comments

  get "/feed" => "home#feed", :as => "feed"

  root "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bizusafo</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= yield :head %>
    <%= csrf_meta_tags %>

    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-53ac86e060676e59"></script>

    <%= auto_discovery_link_tag(:rss, feed_url(:format => :rss)) %>
    <%= auto_discovery_link_tag(:atom, feed_url(:format => :atom)) %>
  </head>
  <body>
    <%= render "shared/facebook_api" %>

    <div class="container">
      <%= render "shared/header" %>
      <%= render "shared/flash_messages" %>
      <div class="row">
        <div id="menu-actions" class="col-md-1 menu-btn-actions">
          <%= render "shared/main_menu" %>
        </div>
        <div class="col-md-10">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render "shared/google_analytics" %>
  </body>
</html>

app/views/layouts/profile.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bizusafo</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= yield :head %>
    <%= csrf_meta_tags %>

    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-53ac86e060676e59"></script>
  </head>
  <body>
    <%= render "shared/facebook_api" %>

    <div class="container">
      <%= render "shared/header" %>
      <%= render "shared/flash_messages" %>

      <div class="row">
        <div class="col-md-1 menu-btn-actions">
          <%= render "shared/main_menu" %>
        </div>
        <div class="col-md-10 profile">
          <%= render "shared/profile" %>
          <%= render "shared/profile_menu" %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>